;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-backslash
        clipboard-kill-region
        indent-for-tab-command
        org-beginning-of-line
        org-ctrl-c-ctrl-c
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        org-transpose-words
        paredit-forward-slurp-sexp
        paredit-open-round
        skeleton-pair-insert-maybe
        smex
        wdired-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        ))
