;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-left-brace
        TeX-insert-backslash
        clipboard-kill-region
        dired-unmark-all-files
        hungry-delete-backward
        hungry-delete-forward
        indent-for-tab-command
        kill-region
        message-beginning-of-line
        org-beginning-of-line
        org-ctrl-c-ctrl-c
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        org-transpose-words
        org-yank
        paredit-backward-kill-word
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-slurp-sexp
        paredit-open-round
        skeleton-pair-insert-maybe
        smex
        transpose-words
        wdired-downcase-word
        wdired-finish-edit
        wdired-upcase-word
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        orgtbl-self-insert-command
        ))
